title: React Native Gstreamer Plugin
email: contact@kalyzee.com

baseurl: "/react-native-gstreamer" # the subpath of your site, e.g. /blog

url: "https://kalyzee.github.io/"

twitter_username: kalyzee
github_username:  kalyzee

# Build settings
markdown: kramdown
remote_theme: kalyzee/jekyll-theme

doc:
  categories:
    presentation:
      url: #presentation
      title: Presentation
    installation:
      url: #installation
      title: Installation
    usage:
      url: #usage
      title: Usage
